// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY7GUnOOwl4JWAXF58ojfbiHdRHJI7LhM',
    appId: '1:719414434481:web:91bc346bfb93d56996a090',
    messagingSenderId: '719414434481',
    projectId: 'l--artisan-dulce',
    authDomain: 'l--artisan-dulce.firebaseapp.com',
    storageBucket: 'l--artisan-dulce.firebasestorage.app',
    measurementId: 'G-F87F6LXZC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnIR6eelYu5I4pQjgLMPI3NloOW0KdiWo',
    appId: '1:719414434481:android:65d45cf92ec83a5c96a090',
    messagingSenderId: '719414434481',
    projectId: 'l--artisan-dulce',
    storageBucket: 'l--artisan-dulce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-2U0cOONpSWwnO1JAApgKzHfvD5DU6iE',
    appId: '1:719414434481:ios:03a9c61068926d2a96a090',
    messagingSenderId: '719414434481',
    projectId: 'l--artisan-dulce',
    storageBucket: 'l--artisan-dulce.firebasestorage.app',
    iosBundleId: 'com.example.simple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-2U0cOONpSWwnO1JAApgKzHfvD5DU6iE',
    appId: '1:719414434481:ios:03a9c61068926d2a96a090',
    messagingSenderId: '719414434481',
    projectId: 'l--artisan-dulce',
    storageBucket: 'l--artisan-dulce.firebasestorage.app',
    iosBundleId: 'com.example.simple',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY7GUnOOwl4JWAXF58ojfbiHdRHJI7LhM',
    appId: '1:719414434481:web:fc5a1cd24100a15896a090',
    messagingSenderId: '719414434481',
    projectId: 'l--artisan-dulce',
    authDomain: 'l--artisan-dulce.firebaseapp.com',
    storageBucket: 'l--artisan-dulce.firebasestorage.app',
    measurementId: 'G-K4D9W2BLFH',
  );

}